### ISSUE TITLE
Two tests failing locally because of OpenSSL Error

### ISSUE THREAD

**Issue by giubueno** [crafters/cielo#32]
Hi guys,

I am having a bit of trouble with the tests. Is it something trivial for you?

Test results:

.FF.............................

Failures:

  1) Cielo::Connection making a request should make a request
     Failure/Error: response = @connection.request! :data => "Anything"
     OpenSSL::SSL::SSLError:
       SSL_connect returned=1 errno=0 state=SSLv3 read server hello A: wrong version number
     # ./lib/cielo/connection.rb:27:in `request!'
     # ./spec/cielo/connection_spec.rb:22:in `block (3 levels) in <top (required)>'

  2) Cielo::Connection passing an access key and a client number should make a request whithout any problem
     Failure/Error: response = @connection2.request! :data => "Anything"
     OpenSSL::SSL::SSLError:
       SSL_connect returned=1 errno=0 state=SSLv3 read server hello A: wrong version number
     # ./lib/cielo/connection.rb:27:in `request!'
     # ./spec/cielo/connection_spec.rb:31:in `block (3 levels) in <top (required)>'

Finished in 1.22 seconds
32 examples, 2 failures

Failed examples:

rspec ./spec/cielo/connection_spec.rb:21 # Cielo::Connection making a request should make a request
rspec ./spec/cielo/connection_spec.rb:30 # Cielo::Connection passing an access key and a client number should make a request whithout any problem

**Comment by giubueno** [comment]
I changed the Connection class to use TLSv1 and all tests passed.
